config/routes.rb
Rails.application.routes.draw do

  get 'all_users' => 'users#view_all_users'
  post 'add_user_to_admin' => 'users#add_user_to_admin'

  post 'add_to_cart' => 'cart#add_to_cart'
  post 'edit_cart_quantity' => 'cart#edit_cart_quantity'
  post 'remove_from_cart' => 'cart#remove_from_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  post 'order_complete' => 'cart#order_complete'

  devise_for :users

  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    before_action :authenticate_user!, except: %i[add_to_cart view_order]

    def add_to_cart
        #create an order earlier using our helper method
        @order = current_order
        # get all the items from our line_item table
        line_item = @order.line_items.find_by(product_id: params[:product_id])

        #check to see if product already exists in our cart to prevent doubles
          if !line_item.blank?
             line_item.update(quantity: line_item.quantity += params[:quantity].to_i)
             line_item.update(line_item_total: line_item.quantity * line_item.product.price)

          else
            #if the item is already in the cart, update the quantity
            line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])

            @order.save
            session[:order_id] = @order.id
            line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

          end
        redirect_back(fallback_location: root_path)
    end

    def view_order
        @order = current_order
    end

    def remove_from_cart
        @order = current_order
        line_item = @order.line_items.find_by(product_id: params[:product_id])
        @order.line_items.delete(line_item)

        @order.save

        redirect_back(fallback_location: view_order_path)
    end

    def edit_cart_quantity
        @order = current_order
        line_item = @order.line_items.find_by(product_id: params[:product_id])
        line_item.update(quantity: params[:quantity])
        line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

        @order.save

        redirect_back(fallback_location: view_order_path)
    end

    def checkout
        line_items = current_order.line_items

        @order = current_order

        unless line_items.empty?
            current_order.update(user_id: current_user.id, subtotal: 0)
            @order = current_order
            
            line_items.each do |line_item|
                line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
                @order.order_items[line_item.product_id] = line_item.quantity
                @order.subtotal += line_item.line_item_total
            end
            @order.save

            @order.update(sales_tax: (@order.subtotal * 0.08))
            @order.update(grand_total: (@order.sales_tax + @order.subtotal))
            session[:order_id] = nil
        end
    end

    def order_complete
        @order = Order.find(params[:order_id])
        @order.line_items.destroy_all
        @amount = (@order.grand_total.to_f.round(2) * 100).to_i

        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )

        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: @amount,
            description: 'Final purchase checkout',
            currency: 'usd'
        )
    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to cart_path
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thanks for shopping with us!</h2>
<p>Please review your order:</p>

<% @order.order_items.each do |k, v| %>
<ul>
    <li><%= Product.find(k).name %>, <%= v %></li>
</ul>
<% end %>

<p>
    <strong>Subtotal:</strong> <%= number_to_currency @order.subtotal %>
</p>

<p>
    <strong>Sales Tax:</strong> <%= number_to_currency @order.sales_tax %>
</p>

<p>
    <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

<div>
   <%= form_tag order_complete_path do %>
        <article>
            <label class="amount">
                <span><%= number_to_currency @order.grand_total %></span>
            </label>
        </article>
        <div>
            <%= hidden_field_tag :order_id, @order.id %>
        </div>

        <script src="http://checkout.stripe.com/checkout.js"
        class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Order #<%= @order.id %>"
        data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
   <% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>
    Order #<%= @order.id %> will be shipping within the next year to you, <%= @order.user.email %>, as soon as possible.
</p>

app/views/cart/view_order.html.erb
<h1>My Cart</h1>
<div>
   <% @order.line_items.each do |line_item| %>
   <li><%= line_item.product.name %></li>
   <li><%= number_to_currency line_item.product.price %></li>
   <li>Qty: <%= line_item.quantity %></li>
   <li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
        <%= form_tag remove_from_cart_path do %>
            <%= hidden_field_tag :product_id, line_item.product_id %>
            <%= submit_tag  "Remove From Cart", class: "btn btn-danger"%>
        <% end %>

        <%= form_tag edit_cart_quantity_path do %>
            <%= hidden_field_tag :product_id, line_item.product_id %>
            <%= number_field_tag :quantity, nil, placeholder: "Change Quantity?" %>
            <%= submit_tag  "Update", class: "btn btn-primary"%>
        <% end %>
   <br>
   <% end %>
</div>

<div>
   <%= link_to "Proceed to Checkout", checkout_path, class: "btn btn-success" %>
</div>