config/routes.rb
Rails.application.routes.draw do

  get 'all_users' => 'users#view_all_users'
  post 'add_user_to_admin' => 'users#add_user_to_admin'

  post 'add_to_cart' => 'cart#add_to_cart'
  post 'edit_cart_quantity' => 'cart#edit_cart_quantity'
  post 'remove_from_cart' => 'cart#remove_from_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  post 'order_complete' => 'cart#order_complete'

  devise_for :users

  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
      @products = Product.all
  end

  def items_by_category
      @products = Product.where(category: params[:category_id])
      @category = Category.find(params[:category_id])
  end

  def items_by_brand
      @products = Product.where(brand: params[:brand])
      @brand = params[:brand]
  end
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/storefront/_products_loop.html.erb
<div class="row">
    <% @products.each do |product| %>
        <div class="col-md-4">
            <div class="well">
                <% if product.image.url != nil %>
                    <p><%= image_tag product.image.url, size: 100 %></p>
                <% end %>

                <h3><%= link_to product.name, product %></h3>
                <p><%= number_to_currency(product.price) %></p>
                <p>
                    <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
                        <span class="glyphicon glyphicon-plus"></span>quick info
                    </a>
                </p>
                <p><%= product.description %></p>
                <br>
                <br>
                <p style="position: absolute; bottom: 20px;"><%= product.brand %></p>
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
                    </div>

                    <div class="modal-body">
                        <p><%= number_to_currency(product.price) %></p>
                        <p><%= product.description %></p>
                        <p><%= product.brand %></p>
                    </div>

                    <div class="modal-footer">
                        <%= form_tag add_to_cart_path do %>
                        <%= hidden_field_tag :product_id, product.id %>
                        <%= number_field_tag :quantity, nil, placeholder: "How many?" %>
                        <%= submit_tag "Add to Cart", class: "btn btn-primary"%>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/storefront/all_items.html.erb
<h1>Whatcha Buyin'?</h1>
<p>Got a  lotta good stuff to show ya</p>

<%= render 'products_loop' %>

app/views/storefront/items_by_brand.html.erb
<h1>All Our <%= @brand %></h1>
<%= render 'products_loop' %>

app/views/storefront/items_by_category.html.erb
<h1>All Our <%= @category.name %></h1>
<%= render 'products_loop' %>