config/routes.rb
Rails.application.routes.draw do

  get 'all_users' => 'users#view_all_users'
  post 'add_user_to_admin' => 'users#add_user_to_admin'

  post 'add_to_cart' => 'cart#add_to_cart'
  post 'edit_cart_quantity' => 'cart#edit_cart_quantity'
  post 'remove_from_cart' => 'cart#remove_from_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  post 'order_complete' => 'cart#order_complete'

  devise_for :users

  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TTS", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Appliances <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% if user_signed_in? %>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  <% else %>
                  <li><%= link_to "Sign In", new_user_session_path %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
          </ul>
        </li>
        <li>
            <% if @order.line_items.length != 0 %>
                <%= link_to view_order_path do %>
                    <i class="fa fa-shopping-cart" style="font-size: 18px;"> (<%= @order.line_items.length %>)</i>
                <% end %>
            <% else %>
                <%= link_to view_order_path do %>
                    <i class="fa fa-shopping-cart" style="font-size: 18px;"></i>
                <% end %>
            <% end %>
        </li>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
        <%= yield %>
    </div>
  </body>
</html>